### ISSUE TITLE
windows下截图，菜单栏无法覆盖

### ISSUE THREAD

**Issue by chenweijianGZ** [pureZjr/electron-shortcut-capture#1]
windows下截图，菜单栏无法覆盖，而且图标会增加了一个，请问有没有办法处理？

**Comment by pureZjr** [comment]
win几

**Comment by pureZjr** [comment]
> windows下截图，菜单栏无法覆盖，而且图标会增加了一个，请问有没有办法处理？
发了个包 ： electron-shortcut-capture@1.0.51 试试
