### ISSUE TITLE
页面没完全加载

### ISSUE THREAD

**Issue by chenweijianGZ** [pureZjr/electron-shortcut-capture#2]
我使用截图时提示‘页面没完全加载’，请问一下是需要怎么处理？我是使用webpack进行构建的程序，除了npm安装外，还需要做哪些配置吗？

**Comment by chenweijianGZ** [comment]
> 我使用截图时提示‘页面没完全加载’，请问一下是需要怎么处理？我是使用webpack进行构建的程序，除了npm安装外，还需要做哪些配置吗？

webpack添加配置 
{
'electron-shortcut-capture'：'require（“electron-shortcut-capture”）'
}

**Comment by changbb** [comment]
> 'electron-shortcut-capture'：'require（“electron-shortcut-capture”）'

electron-vue项目中怎么配置啊
