### ISSUE TITLE
electron-vue整合之后调用show()总是提示“页面没完全加载”

### ISSUE THREAD

**Issue by fjl280855990** [pureZjr/electron-shortcut-capture#4]
如题，请问作者我还有哪里配置没弄好吗？我看displayIds为空

**Comment by pureZjr** [comment]
工具在主线程使用

**Comment by pureZjr** [comment]
> 如题，请问作者我还有哪里配置没弄好吗？我看displayIds为空

工具在主线程使用

**Comment by fjl280855990** [comment]
我是在主线程使用的，我在主线程注册了快捷键，在子线程点击截图给主线程发通信让主线程调用show()或者直接按快捷键截图都不行，都提示这个信息

**Comment by pureZjr** [comment]
> 我是在主线程使用的，我在主线程注册了快捷键，在子线程点击截图给主线程发通信让主线程调用show()或者直接按快捷键截图都不行，都提示这个信息

1.电脑什么操作系统
2.贴代码上来看看

**Comment by fjl280855990** [comment]
win7，electron6.x
![3](https://user-images.githubusercontent.com/35919845/78849096-1b260f80-7a46-11ea-8807-6d465bd31f84.png)
![4](https://user-images.githubusercontent.com/35919845/78849102-1e210000-7a46-11ea-9468-a93d02abaada.png)
![5](https://user-images.githubusercontent.com/35919845/78849103-1eb99680-7a46-11ea-9d15-4ec985f63d6a.png)

**Comment by pureZjr** [comment]
> win7，electron6.x
> ![3](https://user-images.githubusercontent.com/35919845/78849096-1b260f80-7a46-11ea-8807-6d465bd31f84.png)
> ![4](https://user-images.githubusercontent.com/35919845/78849102-1e210000-7a46-11ea-9468-a93d02abaada.png)
> ![5](https://user-images.githubusercontent.com/35919845/78849103-1eb99680-7a46-11ea-9d15-4ec985f63d6a.png)
报 页面没完全加载 是因为，当前的窗口数量跟页面加载数量不等，建议你打断点调试，或者clone 我的项目，在src/main 进程中加上index.ts 文件运行下，看看是什么问题。

```

import { app, globalShortcut } from 'electron'
const debug = require('electron-debug')

import ElectronShortcutCapture from './electron-shortcut-capture'

app.on('ready', () => {
	// undocked
	debug({ devToolsMode: 'right', showDevTools: false })
	const electronShortcutCapture = new ElectronShortcutCapture({
		multiScreen: false,
	})

	globalShortcut.register('alt+shift+w', () => {
		electronShortcutCapture.show()
	})
})

app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') {
		app.quit()
	}
})
```

**Comment by fjl280855990** [comment]
好吧，我再看下，谢谢

**Comment by pureZjr** [comment]
> 好吧，我再看下，谢谢

可不可以

**Comment by fjl280855990** [comment]
displayIds始终为空

**Comment by pureZjr** [comment]
> displayIds始终为空

你在 getLoadedPageDisplayId 里面 打印下displayId，看看什么结果

**Comment by fjl280855990** [comment]
我不是react项目，是vue项目，还是用作者编译好的框架接入的，调用getLoadedPageDisplayId函数返回undefined

**Comment by fjl280855990** [comment]
已经处理了，是webpack配置的问题

**Comment by git-zhanglei** [comment]
> 已经处理了，是webpack配置的问题

遇到了同样的问题，方便问下配置怎么改的吗

**Comment by changbb** [comment]
> undefined

怎么配置的大佬

**Comment by changbb** [comment]
> > 已经处理了，是webpack配置的问题
> 
> 遇到了同样的问题，方便问下配置怎么改的吗

你解决了吗
