### ISSUE TITLE
关于截图中输入文字的BUG

### ISSUE THREAD

**Issue by fjl280855990** [pureZjr/electron-shortcut-capture#5]
第一次截图我输入了一段文字，当我第二次再截图的时候这段文字会再次出现
![QQ截图20200409125503](https://user-images.githubusercontent.com/35919845/78859262-61d53300-7a61-11ea-80dc-6a3f43e89281.png)

**Comment by pureZjr** [comment]
> 第一次截图我输入了一段文字，当我第二次再截图的时候这段文字会再次出现
> ![QQ截图20200409125503](https://user-images.githubusercontent.com/35919845/78859262-61d53300-7a61-11ea-80dc-6a3f43e89281.png)

安装最新包试试

**Comment by fjl280855990** [comment]
OK
